spring:
  config:
    activate:
      on-profile: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://${ip}:3306/reduck?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterSetResults=UTF-8&characterEncoding=UTF-8
    username: root
    password: p39pwt12!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:

    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url:jdbc:h2:mem:testdb;MODE=MySQL
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql : true
        dialect: org.hibernate.dialect.MySQL8Dialect

## local
ip: localhost

